package br.com.hhc.sample.fullstackspringhibernate.database.data.domain;

// Generated 18/03/2015 07:57:17 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstructorClasses generated by hbm2java
 */
@Entity
@Table(name = "INSTRUCTOR_CLASSES")
public class InstructorClasses implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long id;
	private Classes classes;
	private Instructor instructors;
	private Date beginDate;
	private Date endDate;

	public InstructorClasses() {
	}

	
	@Id
	@Column(name = "INSTRUCTOR_CLASSES_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long instructorClassesId) {
		this.id = instructorClassesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLASSES_ID", nullable = false)
	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTRUCTOR_ID", nullable = false)
	public Instructor getInstructors() {
		return this.instructors;
	}

	public void setInstructors(Instructor instructors) {
		this.instructors = instructors;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INS_CLASSES_BEGIN_DATE", nullable = false, length = 7)
	public Date geBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date insClassesBeginDate) {
		this.beginDate = insClassesBeginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INS_CLASSES_END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date insClassesEndDate) {
		this.endDate = insClassesEndDate;
	}

}
